### ISSUE TITLE
dicey chop arguments for creating reads for mappability map

### ISSUE THREAD

**Issue by bzhang19** [gear-genomics/dicey#10]
Hello! I'm interested in generating a mappability map for a genome for Delly germinal CNV calling. There are several arguments for dicey chop including insert size, read length etc. Would I need to set those arguments to whatever match the reads that I'll be using or should they just remind default? Thank you so much for your time.

**Comment by tobiasrausch** [comment]
For standard illumina paired-end libraries the defaults are fine.
