### ISSUE TITLE
dicey index. Core dumped

### ISSUE THREAD

**Issue by vicasze** [gear-genomics/dicey#14]
Hello,

I am getting the following error while indexing a genome:

dicey: /opt/conda/conda-bld/dicey_1718012175577/work/src/sdslLite/include/sdsl/int_vector.hpp:1724: sdsl::int_vector<<anonymous> >::const_reference sdsl::int_vector<<anonymous> >::operator[](const size_type&) const [with unsigned char t_width = 1; const_reference = long unsigned int; size_type = long unsigned int]: Assertion `idx < this->size()' failed.
Aborted (core dumped)

command used:

dicey index -o GCA_024584535.1_ASM2458453v1_genomic.fna.fm9 GCA_024584535.1_ASM2458453v1_genomic.fna.gz

The genome is bgzip. The command works with other genomes.

Any hints?
thank you

**Comment by vicasze** [comment]
PS. fyi: the genome can be found here: https://www.ncbi.nlm.nih.gov/datasets/genome/GCA_024584535.1/

**Comment by tobiasrausch** [comment]
Hmm, I am not sure. For me the command did work. Maybe rename to *.fa ?

`dicey index -o GCA_024584535.1_ASM2458453v1_genomic.fa.fm9 GCA_024584535.1_ASM2458453v1_genomic.fa.gz`

**Comment by vicasze** [comment]
thank you for quick reply!

ok then, strange, I keep running on that error whether is .fa. I also tried on a server (in case was a question of space). It only happens with 2 genomes out of 286 (all fna). I guess I will skip those :)
thanks again

**Comment by tobiasrausch** [comment]
Thanks, maybe the download of the FASTA was somehow corrupted?
