### ISSUE TITLE
NCBI nt database index and search?

### ISSUE THREAD

**Issue by wangzc66** [gear-genomics/dicey#15]
Can dicey search on the nt database？

**Comment by tobiasrausch** [comment]
We didn't try this and the index building is probably a massive undertaking because nt contains AFAIK close to ~100 million sequences and more than 1 trillion bases.

**Comment by wangzhichao1990** [comment]
> We didn't try this and the index building is probably a massive undertaking because nt contains AFAIK close to ~100 million sequences and more than 1 trillion bases.

This requires a lot of disk space and is very slow, so I gave up.
