### ISSUE TITLE
Error with FM-Index

### ISSUE THREAD

**Issue by Wentting** [gear-genomics/dicey#4]
I got an error with "FM-Index cannot be loaded!"

Here is my command

`dicey search -c 45 -g Homo_sapiens.GRCh37.dna.primary_assembly.fa.gz primers.fa -i /dicey/src/primer3_config/`

I am not familar with C++, but i search for the error for a long time and i think there is somthing wrong with the genomeindex.json 
file. But I have load all the reference file from the recommend webset as following: fa.gz file, fa.gz.fai file, fa.gz.gzi file and the fa.fm9 file.

I  really struggled with the error for many days, so it will be very appriciate  for any advise! 

Thank a ton!

**Comment by tobiasrausch** [comment]
Are you using the latest version of dicey?

`dicey --version`

**Comment by Wentting** [comment]
Thank you so much for your reply!

I am sure i am using the lastes version and all the  FM-Indices files were all downloaded and put into one directiry from https://gear.embl.de/data/tracy/

Homo_sapiens.GRCh37.dna.primary_assembly.fa.fm9 
Homo_sapiens.GRCh37.dna.primary_assembly.fa.gz
Homo_sapiens.GRCh37.dna.primary_assembly.fa.gz.fai
Homo_sapiens.GRCh37.dna.primary_assembly.fa.gz.gzi

I dont kown if these are all files I need. And, dicey I am using  was pre-compiled version and downloaded from https://github.com/gear-genomics/dicey/releases

**Comment by tobiasrausch** [comment]
It should be 5 files for each genome build. I think you are missing `Homo_sapiens.GRCh37.dna.primary_assembly.fa.fm9_check`

Please download this file then it should work.

**Comment by Wentting** [comment]
I am so excited It works. Yes I should download the check file！

Thank you sooooooo much for your reply and your amazing work! Hope you have a nice day!
