### ISSUE TITLE
Issues compiling dicey on Mac M1

### ISSUE THREAD

**Issue by Boehmin** [gear-genomics/dicey#7]
I am unable to compile dicey on a Mac (MacBook Pro, M1 Max chip, 32 GB RAM, Ventura 13.4).

I have installed it using Biocanda in a conda environment. When trying to compile it I run into the following issue:

```
(probe_dicey) boehm0002@bz-rgmr01-plm02 dicey % make all
if [ -r src/htslib/Makefile ]; then cd src/htslib && autoreconf -i && ./configure --disable-s3 --disable-gcs --disable-libcurl --disable-plugins && /Library/Developer/CommandLineTools/usr/bin/make && /Library/Developer/CommandLineTools/usr/bin/make lib-static && cd ../../ && touch .htslib; fi
Can't exec "aclocal": No such file or directory at /opt/homebrew/Cellar/autoconf/2.71/share/autoconf/Autom4te/FileUtils.pm line 274.
autoreconf: error: aclocal failed with exit status: 2
make: *** [.htslib] Error 2
```

I was able to figure out that I should install automake as this contains aclocal, but I have a University managed computer and using brew to do this does not work well. Even after installation in admin mode I get the same message.

I then also tried to run dicey using docker afterwards and I run into the following issue when pulling it (I used Docker Desktop):
no matching manifest for linux/arm64/v8 in the manifest list entries

After some digging in stack-overflow I found that this is due to an issue with M1 chips and after resolving that I still received the same error as above. I am now stuck and unable to track down if this is actually a Mac issue or something else.

Many thanks for your help!!

**Comment by tobiasrausch** [comment]
I hope bioconda supports osx-arm64 soon but I am not sure when this is going to happen. Have you tried the singularity images, maybe these work? 

[Dicey releases](https://github.com/gear-genomics/dicey/releases): [https://github.com/gear-genomics/dicey/releases/download/v0.2.5/dicey_v0.2.5.sif](https://github.com/gear-genomics/dicey/releases/download/v0.2.5/dicey_v0.2.5.sif)

**Comment by Boehmin** [comment]
Thanks for such a quick reply Tobias, I tried the singularity images as well - however, I also had issues installing these on the university managed mac... unfortunately.

I managed to get most of the way on my private Mac book (still an old intel chip) and install most things with homebrew. But upon running the dicey padlock command I receive an error message telling me the command does not exist. Something seems to not have been compiled properly. Not sure if you ever stumbled upon the same issue before?

**Comment by tobiasrausch** [comment]
Can you try dicey without subcommands first? Do you see the list of subcommands and what version are you using?

`./src/dicey`

`./src/dicey -v`

**Comment by Boehmin** [comment]
Thank you so much for getting back to me so quickly!

When I run dicey I get the following:
`(dicey) INES-MBP-2018:dicey ines$ dicey
**********************************************************************
Program: Dicey
This is free software, and you are welcome to redistribute it under
certain conditions (BSD License); for license details use '-l'.
This program comes with ABSOLUTELY NO WARRANTY; for details use '-w'.

Dicey (Version: 0.1.7)
Contact: Tobias Rausch (rausch@embl.de)
**********************************************************************

Usage: dicey <command> <arguments>

Commands:

    index        index FASTA reference file
    hunt         search DNA sequences
    search       in-silico PCR


Mappability:

    chop         chop reference into paired-end / single-end reads
    mappability  mappability using read's edit distance (slow)
    mappability2 parse BAM from mapped chopped reads (requires chop + map before)
    blacklist    blacklist certain regions in mappability map
`

When I check for the version I get:
`(dicey) INES-MBP-2018:dicey ines$ dicey -v
Dicey version: v0.1.7
 using Boost: v1.70.0
 using HTSlib: v1.9`

I have some dylib library issues when trying to run ./src/dicey (same for checking the version)
`(dicey) INES-MBP-2018:dicey ines$ ./src/dicey
dyld[82221]: Library not loaded: /usr/local/lib/libhts.3.dylib
  Referenced from: <08EF7E29-142D-3CD4-B313-825BDE61DFE7> /Users/ines/dicey/src/dicey
  Reason: tried: '/usr/local/lib/libhts.3.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/lib/libhts.3.dylib' (no such file), '/usr/local/lib/libhts.3.dylib' (no such file), '/usr/lib/libhts.3.dylib' (no such file, not in dyld cache)
Abort trap: 6
`

**Comment by tobiasrausch** [comment]
I think on Mac you need to set the `DYLD_LIBRARY_PATH` first. In your case:

`export DYLD_LIBRARY_PATH=/Users/ines/dicey/src/htslib/:${DYLD_LIBRARY_PATH}`

`./src/dicey`

**Comment by Boehmin** [comment]
Amazing, thank you so much, I can now get it to run with

`./src/dicey padlock -g data/Mus_musculus.GRCm38.dna.primary_assembly.fa.gz -t Mus_musculus.GRCm39.109.gtf.gz -b data/bar.fa ENSMUSG00000031613 -m 15`

However, my out.tsv is empty.
It runs through GTF feature parsing, load barcodes, compute padlocks and Done without any error messages.

**Comment by tobiasrausch** [comment]
Sure, a 15-mer is almost never unique in a mammalian-sized genome, especially with default `dicey padlock` options which require that even the 1-bp edit distance of the 15-mer is unique. The default options with a 20bp arm length should return some hits:

`./src/dicey padlock -g Mus_musculus.GRCm38.dna.primary_assembly.fa.gz -t Mus_musculus.GRCm38.dna.primary_assembly.gtf.gz -b bar.fa.gz ENSMUSG00000031613 -m 20`

Or if you want to have shorter probes, you have to set the distance to 0, i.e., only the 15-mer is unique but not the neighbours:

`./src/dicey padlock -m 15 -d 0 ...`

Even less stringent and not recommended is to accept probes where only one of the two arms is unique:

`./src/dicey padlock -m 15 -d 0 -p ...`

ps: The last option, I just recently added so you might have to get the latest code and re-compile:

`git pull && make all && make install`
